services:
  auth-db:
    image: postgres:latest
    hostname: auth_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-auth}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  auth-api:
    build: .
    depends_on:
      - auth-db
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:auth_db@postgres:5432/auth?schema=public}
    restart: always

volumes:
  postgres-data:
