services:
  mu_auth_db:
    image: postgres:17-alpine

    # Hostname for which the service will be reachable
    hostname: ${mu_auth_db_HOSTNAME:-mu_auth_db}

    # Ports exposed to OTHER SERVICES but NOT the HOST machine
    expose:
      - ${mu_auth_db_INTERNAL_PORT:-5432}

    restart: always

    environment:
      POSTGRES_USER: ${mu_auth_db_USER:-postgres}
      POSTGRES_PASSWORD: ${mu_auth_db_PASSWORD:-meetUN}
      POSTGRES_DB: ${mu_auth_db_DB:-meetun}
      PGPORT: ${mu_auth_db_INTERNAL_PORT:-5432}

    volumes:
      - mu-auth-db-data:/var/lib/postgresql/data

  mu_auth_ms:
    build: .
    depends_on:
      - mu_auth_db
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://user_db:meetUN@auth_db:5432/auth?schema=public}
      REDIS_CONNECTION_STRING: ${REDIS_CONNECTION_STRING:-redis://whitelist:6379}
      JWT_SECRET: ${JWT_SECRET:-defaultsecret}
      USER_TOKEN_EXPIRATION_TIME: ${USER_TOKEN_EXPIRATION_TIME:-5m}
    restart: on-failure:2 # NOTE: Service won't restart after failing twice

volumes:
  mu-auth-db-data:
